### ISSUE TITLE
Module not found: Can't resolve 'react-addons-css-transition-group' 

### ISSUE THREAD

**Issue by danny-dang** [edwardfxiao/react-minimal-datetime-range#3]
`react-addons-css-transition-group` is not listed in dependencies, however, it is listed in peerDependencies. Therefore, this package is not automatically installed when install `react-minimal-datetime-range` and caused this error.

Perhaps you should move those peerDependencies to dependencies for easier installment ?

**Comment by edwardfhsiao** [comment]
Hi there, I am not sure if it is a good idea to install the dependencies automatically. From my experience, it may cause version conflict. But I am not sure about it.
