### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by HarkiratShopism1** [edwardfxiao/react-minimal-datetime-range#8]
Hey brother,

your project "react-minimal-datetime-range" is very nicely done and I am using DateRangePicker component for one of my client and I want to know that is there any way I can automatically set an ending date when the start date gets selected by the user. 
harkirat.shopism@gmail.com this is my email please email me.

Thanks

**Comment by edwardfxiao** [comment]
Hi,

Thank you for your report, please try `v2.0.8` see if it works, and can you also help me test everything else to make sure it does not break anything? Thanks

```js

<RangePicker
 duration={2} // day count. default is 0. set end date will be add 2 days automatically when start date is picked
  ...
/>
```

**Comment by HarkiratShopism1** [comment]
Hi Bro,

Thank you for your response I will try it and surely will help you test out this feature. Please do let me know if there is any update to this.

**Comment by HarkiratShopism1** [comment]
> 

Hi,

duration is working fine but there's a bug. When I tried to click on to the start date 1st and 2nd time it haven't worked but worked at third click. It should work at first click. Whenever a start date is clicked the end date should automatically get selected as startDate + duration.     

Thank you

**Comment by edwardfxiao** [comment]
What browser are you using? I cannot reproduce the problem. Can you provide a screen recording of the issue?

**Comment by edwardfxiao** [comment]
Right now, my plan works like this: the user provides a duration of 2, then selects the start date (let's say August 1), and an end date of August 3 will be automatically chosen. Finally, the user clicks 'confirm' to set the value.

Does this meet your requirements?

**Comment by HarkiratShopism1** [comment]
My requirement goes like this
Duration is preset to 28days 
User clicks and open the dateSelector
User clicks on a date -> end date gets automatically selected. That is staryDate + duration(in Days) = endDate
Something like this...

I am using MSedge

**Comment by edwardfxiao** [comment]
I see the issue now, but I cannot reproduce it, maybe you could make a codesandbox for me?

**Comment by edwardfxiao** [comment]
I think this works fine, right? When you uncomment the `duration` https://codesandbox.io/s/index-z90y9?file=/src/index.js

**Comment by edwardfxiao** [comment]
Ok, I see the issue, let me debug

**Comment by HarkiratShopism1** [comment]
Should I create a sandbox ?

**Comment by edwardfxiao** [comment]
No, I did a quick fix for it, bug please provide an empty array of defaultDates (`defaultDates={[]}` )for now
```js
<RangePicker
       ...
              placeholder={['Start Time', 'End Time']}
              defaultDates={[]}
              onConfirm={res => console.log(res, 1)}
              onClose={() => console.log('closed')}
              duration={2} // day count default is 0. End date will be automatically added 2 days when the start date is picked.
       ...
 />
```

**Comment by HarkiratShopism1** [comment]
Ok alright will test and confirm 

Thank you

**Comment by HarkiratShopism1** [comment]
Hi Brother,

Its working fine as required. 

Thank you for your time and help bro...
