### ISSUE TITLE
How can I disable all the dates before current date.

### ISSUE THREAD

**Issue by HarkiratShopism1** [edwardfxiao/react-minimal-datetime-range#9]
I am using "duration" to pick from a certain date to a certain date and I want to disable all the previous dates so that the user can not select them as the first date. How can I do this.

**Comment by edwardfxiao** [comment]
Let's say user select Jan 01 2024, and the duration is 2, the end date is automatically set Jan 03 2024, and you want to disable all the dates before Jan 01 2024? And user can only select Jan 02 2024 and after and so on? Meaning that user cannot select back again?

**Comment by HarkiratShopism1** [comment]
Yes exactly

**Comment by edwardfxiao** [comment]
I don't think it's possible for now

**Comment by edwardfxiao** [comment]
@HarkiratShopism1 Hi, in verison```2.1.0``` I provide a `onChooseDate` property for this. Each time you clicked a date, you set `supportDateRange` with it.

Something like this:

```js
const [mySupportDateRange, setMySupportDateRange] = useState(['2024-01-10', ''])
...
<RangePicker
  ...
  supportDateRange={stateSupportedDates[0]}
  duration={2}
  onChooseDate={res => {
    stateSupportedDates[1](prev => {
      prev[0] = res.value;
      return prev;
    });
  }}
/>
```
Try if it works.
